### ISSUE TITLE
ModuleNotFoundError: No module named 'gvbenchmark'

### ISSUE THREAD

**Issue by KangolHsu** [OpenGVLab/gv-benchmark#4]
CMD RUN:    mim train mmcls configs/cls/linear_probe/mnb4_Up-E-C_pretrain_flowers_10p.py

LOG:

Training command is python c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\mmcls\.mim\tools\train.py configs/cls/linear_probe/mnb4_Up-E-C_pretrain_flowers_10p.py --gpus 1 --launcher none.
Traceback (most recent call last):
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\mmcv\utils\misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gvbenchmark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\mmcls\.mim\tools\train.py", line 203, in <module>
    main()
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\mmcls\.mim\tools\train.py", line 92, in main
    cfg = Config.fromfile(args.config)
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\mmcv\utils\config.py", line 337, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\mmcv\utils\misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError
Traceback (most recent call last):
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xukang\miniconda3\envs\torch1.7.0\Scripts\mim.exe\__main__.py", line 7, in <module>
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\mim\commands\train.py", line 107, in cli
    other_args=other_args)
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\site-packages\mim\commands\train.py", line 256, in train
    cmd, env=dict(os.environ, MASTER_PORT=str(port)))
  File "c:\users\xukang\miniconda3\envs\torch1.7.0\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'c:\\users\\xukang\\miniconda3\\envs\\torch1.7.0\\lib\\site-packages\\mmcls\\.mim\\tools\\train.py', 'configs/cls/linear_probe/mnb4_Up-E-C_pretrain_flowers_10p.py', '--gpus', '1', '--launcher', 'none']' returned non-zero exit status 1.

**Comment by MartinYYYYan** [comment]
Maybe you need to specify the python path before 'mim test', like PYTHONPATH='.':$PYTHONPATH mim test ${TASK} ${CONFIG} \
 --checkpoint  /home/ideal/IMAGE/gv-benchmark/dyan/pretrained_weights/INTERN-mnb4-Up-E-D-95897bb8c.pth.tar \
 --gpus-per-node ${GPUS_PER_NODE} --cpus-per-task ${CPUS_PER_TASK} --work-dir ${WORK_DIR} --eval acc
